name: flutter_application_1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  # cupertino_icons: null
  dio: null
  easy_localization: null
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_native_splash: null
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  freezed: null
  freezed_annotation: null
  get: null
  get_it: null
  intl: null
  json_annotation: null
  json_serializable: null
  pretty_dio_logger: null
  retrofit: null
  retrofit_generator: null

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
